"""
Bug condition exploration property-based tests for color fidelity pattern loss.

**Validates: Requirements 2.1, 2.2, 2.3, 2.4**

This test validates that when users upload garments with obvious patterns and colors,
the warped_layer generated by catvton_color_fidelity_spatial preserves the original
RGB values instead of becoming nearly black.

**CRITICAL**: This test is EXPECTED TO FAIL on unfixed code - failure confirms the bug exists.
When the test fails, it will surface counterexamples showing warped_layer RGB values < 20
instead of preserving the original colors (~180).

**NOTE**: This test encodes the expected behavior - it will validate the fix when it passes
after implementation.
"""

from __future__ import annotations

import numpy as np
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st
from PIL import Image

# ============================================================================
# Test Image Generators
# ============================================================================


def make_patterned_garment(
    size: tuple[int, int],
    pattern_type: str,
    colors: list[tuple[int, int, int]],
) -> Image.Image:
    """
    Generate a garment image with obvious patterns.

    Args:
        size: (width, height) of the image
        pattern_type: "checkerboard", "stripes", "stars", "cartoon", "embroidery"
        colors: List of RGB tuples to use in the pattern

    Returns:
        PIL Image with the specified pattern
    """
    width, height = size
    arr = np.zeros((height, width, 3), dtype=np.uint8)

    if pattern_type == "checkerboard":
        # Create checkerboard pattern
        square_size = max(8, min(width, height) // 16)
        for y in range(height):
            for x in range(width):
                sx = (x // square_size) % len(colors)
                sy = (y // square_size) % len(colors)
                color_idx = (sx + sy) % len(colors)
                arr[y, x] = colors[color_idx]

    elif pattern_type == "stripes":
        # Create horizontal stripes
        stripe_height = max(8, height // 10)
        for y in range(height):
            color_idx = (y // stripe_height) % len(colors)
            arr[y, :] = colors[color_idx]

    elif pattern_type == "stars":
        # Create colorful stars on a base color
        base_color = colors[0]
        arr[:, :] = base_color

        # Add star-like patterns (simplified as circles)
        num_stars = 15
        for i in range(num_stars):
            # Deterministic star positions based on index
            cx = (i * 137) % width  # Use prime number for distribution
            cy = (i * 211) % height
            radius = max(10, min(width, height) // 20)
            star_color = colors[(i % (len(colors) - 1)) + 1]

            # Draw circle
            for y in range(max(0, cy - radius), min(height, cy + radius)):
                for x in range(max(0, cx - radius), min(width, cx + radius)):
                    if (x - cx) ** 2 + (y - cy) ** 2 <= radius**2:
                        arr[y, x] = star_color

    elif pattern_type == "cartoon":
        # Create cartoon-like pattern with bold colors
        base_color = colors[0]
        arr[:, :] = base_color

        # Add cartoon character-like shapes (simplified as rectangles and circles)
        # Head (circle)
        head_cx = width // 2
        head_cy = height // 3
        head_radius = min(width, height) // 6
        head_color = colors[1] if len(colors) > 1 else (255, 200, 150)

        for y in range(max(0, head_cy - head_radius), min(height, head_cy + head_radius)):
            for x in range(max(0, head_cx - head_radius), min(width, head_cx + head_radius)):
                if (x - head_cx) ** 2 + (y - head_cy) ** 2 <= head_radius**2:
                    arr[y, x] = head_color

        # Body (rectangle)
        body_color = colors[2] if len(colors) > 2 else (100, 150, 255)
        body_top = head_cy + head_radius
        body_bottom = min(height, body_top + height // 3)
        body_left = head_cx - head_radius // 2
        body_right = head_cx + head_radius // 2
        arr[body_top:body_bottom, body_left:body_right] = body_color

    elif pattern_type == "embroidery":
        # Create embroidery-like pattern with fine details
        base_color = colors[0]
        arr[:, :] = base_color

        # Add embroidery-like lines and dots
        embroidery_color = colors[1] if len(colors) > 1 else (200, 50, 50)

        # Vertical lines
        for x in range(width // 4, width, width // 8):
            if x < width:
                arr[:, x : min(x + 2, width)] = embroidery_color

        # Horizontal lines
        for y in range(height // 4, height, height // 8):
            if y < height:
                arr[y : min(y + 2, height), :] = embroidery_color

        # Dots at intersections
        for y in range(height // 4, height, height // 8):
            for x in range(width // 4, width, width // 8):
                if y < height and x < width:
                    dot_radius = 3
                    for dy in range(-dot_radius, dot_radius + 1):
                        for dx in range(-dot_radius, dot_radius + 1):
                            if (
                                dx**2 + dy**2 <= dot_radius**2
                                and 0 <= y + dy < height
                                and 0 <= x + dx < width
                            ):
                                arr[y + dy, x + dx] = (
                                    colors[2] if len(colors) > 2 else (255, 200, 50)
                                )

    return Image.fromarray(arr, mode="RGB")


def calculate_rgb_mean_non_transparent(image: Image.Image, alpha_threshold: int = 128) -> float:
    """
    Calculate the mean RGB value in non-transparent regions of an RGBA image.

    Args:
        image: PIL Image in RGBA mode
        alpha_threshold: Minimum alpha value to consider a pixel non-transparent

    Returns:
        Mean RGB value across all non-transparent pixels
    """
    if image.mode != "RGBA":
        image = image.convert("RGBA")

    arr = np.array(image, dtype=np.float32)
    alpha = arr[:, :, 3]

    # Find non-transparent pixels
    non_transparent_mask = alpha > alpha_threshold

    if not non_transparent_mask.any():
        # No non-transparent pixels, return 0
        return 0.0

    # Calculate mean RGB in non-transparent regions
    rgb_values = arr[:, :, :3][non_transparent_mask]
    return float(rgb_values.mean())


def calculate_pattern_score(image: Image.Image) -> float:
    """
    Calculate a pattern score for the image based on color variance.

    Returns:
        Pattern score between 0 and 1 (higher = more patterned)
    """
    import cv2

    arr = np.array(image.convert("RGB"))
    hsv = cv2.cvtColor(arr, cv2.COLOR_RGB2HSV).astype(np.float32)
    sat = hsv[:, :, 1]

    # Calculate saturation variance as a proxy for pattern complexity
    sat_std = float(sat.std())
    # Normalize to 0-1 range (empirically, std > 30 indicates patterns)
    pattern_score = min(1.0, sat_std / 50.0)

    return pattern_score


def calculate_color_variance(image: Image.Image) -> float:
    """
    Calculate color variance in the image.

    Returns:
        Color variance (higher = more color variation)
    """
    arr = np.array(image.convert("RGB"), dtype=np.float32)

    # Calculate variance across all RGB channels
    r_var = float(arr[:, :, 0].var())
    g_var = float(arr[:, :, 1].var())
    b_var = float(arr[:, :, 2].var())

    # Return average variance
    return (r_var + g_var + b_var) / 3.0


# ============================================================================
# Property-Based Test Strategies
# ============================================================================


@st.composite
def patterned_garment_strategy(draw):
    """
    Generate garment images with patterns/multiple colors.

    Scoped to garments with pattern_score > 0.3 OR color_variance > 30
    """
    # Choose pattern type
    pattern_type = draw(
        st.sampled_from(
            [
                "checkerboard",
                "stripes",
                "stars",
                "cartoon",
                "embroidery",
            ]
        )
    )

    # Choose size (typical garment image sizes)
    width = draw(st.integers(min_value=256, max_value=768))
    height = draw(st.integers(min_value=256, max_value=768))

    # Choose colors (at least 2 colors for patterns)
    num_colors = draw(st.integers(min_value=2, max_value=5))
    colors = []
    for _ in range(num_colors):
        r = draw(st.integers(min_value=50, max_value=255))
        g = draw(st.integers(min_value=50, max_value=255))
        b = draw(st.integers(min_value=50, max_value=255))
        colors.append((r, g, b))

    # Generate the garment image
    garment = make_patterned_garment((width, height), pattern_type, colors)

    # Verify it meets the scoping criteria
    pattern_score = calculate_pattern_score(garment)
    color_variance = calculate_color_variance(garment)

    # Only return if it meets the bug condition criteria
    if pattern_score > 0.3 or color_variance > 30:
        return {
            "garment": garment,
            "pattern_type": pattern_type,
            "pattern_score": pattern_score,
            "color_variance": color_variance,
        }
    else:
        # Reject and retry
        # This shouldn't happen often with our generator, but just in case
        return draw(patterned_garment_strategy())


def make_simple_person_image(size: tuple[int, int] = (512, 768)) -> Image.Image:
    """Create a simple person-like image for testing."""
    width, height = size
    arr = np.zeros((height, width, 3), dtype=np.uint8)

    # Background
    arr[:, :] = (200, 200, 200)

    # Simple person silhouette (rectangle for body)
    body_left = width // 3
    body_right = 2 * width // 3
    body_top = height // 4
    body_bottom = 3 * height // 4

    # Skin tone for body
    arr[body_top:body_bottom, body_left:body_right] = (220, 180, 150)

    return Image.fromarray(arr, mode="RGB")


def make_simple_catvton_result(size: tuple[int, int] = (512, 768)) -> Image.Image:
    """Create a simple CatVTON result image for testing."""
    width, height = size
    arr = np.zeros((height, width, 3), dtype=np.uint8)

    # Background
    arr[:, :] = (180, 180, 180)

    # Person with garment area (slightly different color)
    body_left = width // 3
    body_right = 2 * width // 3
    body_top = height // 4
    body_bottom = 3 * height // 4

    # Garment area (gray - this is what should be replaced with pattern)
    arr[body_top:body_bottom, body_left:body_right] = (150, 150, 150)

    return Image.fromarray(arr, mode="RGB")


# ============================================================================
# Bug Condition Exploration Property Test
# ============================================================================


@settings(
    max_examples=3,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow],
)
@given(garment_data=patterned_garment_strategy())
def test_bug_condition_warped_layer_preserves_color_information(garment_data: dict):
    """
    **Property 1: Bug Condition - Warped Layer Preserves Color Information**

    **Validates: Requirements 2.1, 2.2, 2.3, 2.4**

    For any garment image with patterns or multiple colors (pattern_score > 0.3 OR
    color_variance > 30), the warped_layer generated by catvton_color_fidelity_spatial
    SHALL influence the result such that:

    1. The result RGB mean in the garment region is > 20.0 (not nearly black)
    2. The result differs from catvton_result in the garment region (warped_layer has influence)
    3. The result's color variance (pattern) is preserved, not collapsed to uniform gray

    **CRITICAL**: This test is EXPECTED TO FAIL on unfixed code.
    Failure confirms the bug exists (warped_layer has no influence on result).

    **NOTE**: The blending formula is:
    result = warped_layer * alpha * strength + catvton * (1 - alpha * strength).
    The result CANNOT equal the original garment color because catvton also contributes.
    Instead, we verify the warped_layer is actually influencing the result.
    """
    from app.services.tryon_v2.warp_engine import catvton_color_fidelity_spatial

    garment = garment_data["garment"]
    pattern_type = garment_data["pattern_type"]
    pattern_score = garment_data["pattern_score"]
    color_variance = garment_data["color_variance"]

    # Create test inputs
    catvton_result = make_simple_catvton_result((512, 768))
    person_image = make_simple_person_image((512, 768))

    # Calculate original garment statistics
    original_color_var = calculate_color_variance(garment)

    # Call the function under test
    result, metadata = catvton_color_fidelity_spatial(
        catvton_result=catvton_result,
        original_garment=garment,
        person_image=person_image,
        garment_category="top",
        fidelity_strength=0.75,
    )

    # Extract garment region from result and catvton_result
    result_arr = np.array(result.convert("RGB"), dtype=np.float32)
    catvton_arr = np.array(catvton_result.convert("RGB"), dtype=np.float32)

    height, width = result_arr.shape[:2]
    # Garment region: middle third width, middle half height
    gr_slice = (slice(height // 4, 3 * height // 4), slice(width // 3, 2 * width // 3))
    garment_region = result_arr[gr_slice]
    catvton_region = catvton_arr[gr_slice]

    result_rgb_mean = float(garment_region.mean())

    # Assertion 1: RGB mean should be > 20.0 (not nearly black)
    assert result_rgb_mean > 20.0, (
        f"Bug detected: Result RGB mean is {result_rgb_mean:.2f} (nearly black) "
        f"for {pattern_type} garment with pattern_score={pattern_score:.3f}, "
        f"color_variance={color_variance:.2f}. "
        f"Expected RGB mean > 20.0 to preserve pattern visibility."
    )

    # Assertion 2: Result should differ from catvton_result in garment region
    # This proves the warped_layer is actually contributing to the result.
    # If warped_layer has zero influence, result == catvton_result.
    catvton_rgb_mean = float(catvton_region.mean())
    diff_from_catvton = abs(result_rgb_mean - catvton_rgb_mean)
    assert diff_from_catvton > 1.0, (
        f"Bug detected: Result RGB mean ({result_rgb_mean:.2f}) is nearly identical to "
        f"catvton_result RGB mean ({catvton_rgb_mean:.2f}), diff={diff_from_catvton:.2f}. "
        f"The warped_layer has no influence on the result. "
        f"Pattern type: {pattern_type}, pattern_score={pattern_score:.3f}."
    )

    # Assertion 3: Result color variance should be > 0 (not uniform gray)
    # If the pattern is lost, the garment region becomes uniform.
    result_var = float(garment_region.reshape(-1, 3).var(axis=0).mean())
    assert result_var > 0.5, (
        f"Bug detected: Result color variance is {result_var:.2f} (nearly uniform). "
        f"Original garment color variance: {original_color_var:.2f}. "
        f"Pattern type: {pattern_type}. The pattern appears to be lost."
    )

    print(
        f"✓ Pattern preserved: {pattern_type} "
        f"(result RGB={result_rgb_mean:.2f}, catvton RGB={catvton_rgb_mean:.2f}, "
        f"diff={diff_from_catvton:.2f}, var={result_var:.2f}, "
        f"pattern_score={pattern_score:.3f}, color_variance={color_variance:.2f})"
    )


# ============================================================================
# Manual Test Runner
# ============================================================================


def main():
    """Run the bug condition exploration test manually."""
    print("=" * 80)
    print("Bug Condition Exploration: Color Fidelity Pattern Loss")
    print("=" * 80)
    print()
    print("This test verifies that the warped_layer influences the result.")
    print("On unfixed code, the warped_layer has no effect (result ≈ catvton_result).")
    print()
    print("Running property-based test with Hypothesis...")
    print()

    # Run the test
    try:
        test_bug_condition_warped_layer_preserves_color_information()
        print()
        print("=" * 80)
        print("Test PASSED - Bug is fixed!")
        print("=" * 80)
        print()
        print("The warped_layer is correctly influencing the result.")
    except AssertionError as e:
        print()
        print("=" * 80)
        print("EXPECTED: Test FAILED (Bug Confirmed)")
        print("=" * 80)
        print()
        print(f"Counterexample found: {e}")
        print()
        print("This confirms the bug exists. Proceed with fix implementation.")
    except Exception as e:
        print()
        print("=" * 80)
        print("ERROR: Test encountered an unexpected error")
        print("=" * 80)
        print()
        print(f"Error: {type(e).__name__}: {e}")
        import traceback

        traceback.print_exc()


# ============================================================================
# Preservation Property Tests (Task 2)
# ============================================================================


@st.composite
def solid_color_garment_strategy(draw):
    """
    Generate solid color garment images (pattern_score <= 0.3 AND color_variance <= 30).

    These garments should NOT trigger the bug - they should work correctly in both
    unfixed and fixed code.
    """
    # Choose size (typical garment image sizes)
    width = draw(st.integers(min_value=256, max_value=768))
    height = draw(st.integers(min_value=256, max_value=768))

    # Choose a single solid color
    r = draw(st.integers(min_value=50, max_value=255))
    g = draw(st.integers(min_value=50, max_value=255))
    b = draw(st.integers(min_value=50, max_value=255))

    # Create solid color image
    arr = np.zeros((height, width, 3), dtype=np.uint8)
    arr[:, :] = (r, g, b)

    garment = Image.fromarray(arr, mode="RGB")

    # Verify it meets the solid color criteria
    pattern_score = calculate_pattern_score(garment)
    color_variance = calculate_color_variance(garment)

    # Should be solid color (low pattern score and low color variance)
    assert pattern_score <= 0.3, f"Generated garment has pattern_score={pattern_score:.3f} > 0.3"
    assert color_variance <= 30, f"Generated garment has color_variance={color_variance:.2f} > 30"

    return {
        "garment": garment,
        "color": (r, g, b),
        "pattern_score": pattern_score,
        "color_variance": color_variance,
    }


@settings(
    max_examples=3,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow],
)
@given(garment_data=solid_color_garment_strategy())
def test_preservation_solid_color_garments_unchanged(garment_data: dict):
    """
    **Property 2: Preservation - Solid Color Garments Unchanged**

    **Validates: Requirements 3.1**

    For any garment image that is solid color (pattern_score <= 0.3 AND color_variance <= 30),
    the code SHALL produce consistent results, preserving all existing functionality for
    solid-color garments.

    **IMPORTANT**: This test should PASS on unfixed code (confirms baseline behavior to preserve).

    This test verifies that solid color garments continue to work correctly - the function
    completes without errors and produces output (even if the warped_layer is currently
    all zeros due to the bug, the function should still complete).

    **OBSERVATION**: On unfixed code, warped_layer is all zeros (R=0, G=0, B=0, A=0),
    so the result falls back to the original catvton_result. This is the baseline behavior
    we need to preserve for solid colors.
    """
    from app.services.tryon_v2.warp_engine import catvton_color_fidelity_spatial

    garment = garment_data["garment"]
    color = garment_data["color"]
    pattern_score = garment_data["pattern_score"]
    color_variance = garment_data["color_variance"]

    # Create test inputs
    catvton_result = make_simple_catvton_result((512, 768))
    person_image = make_simple_person_image((512, 768))

    # Call the function under test
    result, metadata = catvton_color_fidelity_spatial(
        catvton_result=catvton_result,
        original_garment=garment,
        person_image=person_image,
        garment_category="top",
        fidelity_strength=0.75,
    )

    # Verify that the function completes successfully
    assert result is not None, "Function should return a result"
    assert (
        metadata.get("engine") == "catvton_color_fidelity_spatial"
    ), "Metadata should indicate spatial engine was used"

    # Extract garment region from result
    result_arr = np.array(result.convert("RGB"), dtype=np.float32)
    height, width = result_arr.shape[:2]
    garment_region = result_arr[
        height // 4 : 3 * height // 4,
        width // 3 : 2 * width // 3,
    ]

    result_rgb_mean = float(garment_region.mean())

    # On unfixed code, warped_layer is all zeros, so result falls back to catvton_result
    # The catvton_result we created has RGB mean around 150 (gray garment area)
    # So we expect result to be close to that baseline

    # Baseline behavior: function completes and produces output in reasonable range
    assert 100.0 < result_rgb_mean < 200.0, (
        f"Result RGB mean is {result_rgb_mean:.2f}, outside expected baseline range [100, 200]. "
        f"Original color={color}, pattern_score={pattern_score:.3f}, "
        f"color_variance={color_variance:.2f}"
    )

    print(
        f"✓ Solid color baseline preserved: color={color} "
        f"(result RGB={result_rgb_mean:.2f}, "
        f"pattern_score={pattern_score:.3f}, color_variance={color_variance:.2f})"
    )


def test_preservation_face_protection_continues_to_work():
    """
    **Property 2: Preservation - Face Protection Functionality**

    **Validates: Requirements 3.4**

    The face protection functionality SHALL continue to work correctly, ensuring that
    the garment layer does not cover the face region.

    **IMPORTANT**: This test should PASS on unfixed code (confirms baseline behavior to preserve).

    This test verifies that the face protection mask is correctly applied and that
    the face region is not covered by the garment layer.
    """
    from app.services.tryon_v2.warp_engine import catvton_color_fidelity_spatial

    # Create a patterned garment
    garment = make_patterned_garment(
        (512, 512),
        "stars",
        [(255, 255, 255), (255, 0, 0), (0, 0, 255)],
    )

    # Create test inputs with a clear face region
    catvton_result = make_simple_catvton_result((512, 768))
    person_image = make_simple_person_image((512, 768))

    # Call the function under test
    result, metadata = catvton_color_fidelity_spatial(
        catvton_result=catvton_result,
        original_garment=garment,
        person_image=person_image,
        garment_category="top",  # Only tops need face protection
        fidelity_strength=0.75,
    )

    # Verify that the result was generated successfully
    assert result is not None, "Function should return a result"
    assert (
        metadata.get("engine") == "catvton_color_fidelity_spatial"
    ), "Metadata should indicate spatial engine was used"

    # Extract face region (top 20% of image)
    result_arr = np.array(result.convert("RGB"), dtype=np.float32)
    height, width = result_arr.shape[:2]
    face_region = result_arr[0 : height // 5, :]

    # The face region should not be completely covered by the garment pattern
    # (it should retain the original catvton_result colors in the face area)
    catvton_arr = np.array(catvton_result.convert("RGB"), dtype=np.float32)
    catvton_face_region = catvton_arr[0 : height // 5, :]

    # Calculate similarity between result face region and original catvton face region
    # They should be very similar (face protection working)
    face_diff = np.abs(face_region - catvton_face_region).mean()

    # Face region should be very similar to original (difference < 10)
    # This confirms face protection is working
    assert face_diff < 10.0, (
        f"Face region was modified too much (diff={face_diff:.2f}), "
        f"suggesting face protection may not be working correctly"
    )

    print(f"✓ Face protection working: face region diff={face_diff:.2f} < 10.0")


def test_preservation_hand_protection_continues_to_work():
    """
    **Property 2: Preservation - Hand Protection Functionality**

    **Validates: Requirements 3.4**

    The hand protection functionality SHALL continue to work correctly, ensuring that
    the garment layer does not cover hand regions detected via wrist keypoints.

    **IMPORTANT**: This test should PASS on unfixed code (confirms baseline behavior to preserve).

    This test verifies that hand regions are protected from garment overlay.
    """
    from app.services.tryon_v2.warp_engine import catvton_color_fidelity_spatial

    # Create a patterned garment
    garment = make_patterned_garment(
        (512, 512),
        "checkerboard",
        [(255, 255, 255), (0, 0, 0)],
    )

    # Create test inputs
    catvton_result = make_simple_catvton_result((512, 768))
    person_image = make_simple_person_image((512, 768))

    # Call the function under test
    result, metadata = catvton_color_fidelity_spatial(
        catvton_result=catvton_result,
        original_garment=garment,
        person_image=person_image,
        garment_category="top",
        fidelity_strength=0.75,
    )

    # Verify that the result was generated successfully
    assert result is not None, "Function should return a result"
    assert (
        metadata.get("engine") == "catvton_color_fidelity_spatial"
    ), "Metadata should indicate spatial engine was used"

    # The function should complete without errors
    # Hand protection is applied internally via wrist keypoint detection
    # We verify that the function runs successfully and produces output

    result_arr = np.array(result.convert("RGB"), dtype=np.float32)
    result_rgb_mean = float(result_arr.mean())

    # Result should be reasonable (not all black or all white)
    assert 20.0 < result_rgb_mean < 240.0, (
        f"Result RGB mean is {result_rgb_mean:.2f}, which is outside reasonable range. "
        f"This suggests hand protection or overall processing may have failed."
    )

    print(f"✓ Hand protection working: result RGB mean={result_rgb_mean:.2f} in reasonable range")


def test_preservation_realism_pass_continues_to_work():
    """
    **Property 2: Preservation - Realism Pass (Wrinkles and Shadows)**

    **Validates: Requirements 3.5**

    The realism pass functionality (wrinkles and shadows) SHALL continue to work correctly
    for garments with low pattern scores (pattern_score <= 0.40).

    **IMPORTANT**: This test should PASS on unfixed code (confirms baseline behavior to preserve).

    This test verifies that the realism pass (fold darkening and edge shadows) is applied
    correctly for solid/low-pattern garments.
    """
    from app.services.tryon_v2.warp_engine import catvton_color_fidelity_spatial

    # Create a solid color garment (low pattern score, should trigger realism pass)
    garment = make_patterned_garment(
        (512, 512),
        "stripes",  # Simple stripes, but with similar colors to keep pattern_score low
        [(200, 200, 200), (210, 210, 210)],  # Very similar colors
    )

    # Verify pattern score is low enough to trigger realism pass
    pattern_score = calculate_pattern_score(garment)
    assert pattern_score <= 0.40, (
        f"Test garment has pattern_score={pattern_score:.3f} > 0.40, "
        f"which would skip realism pass. Adjust test garment."
    )

    # Create test inputs
    catvton_result = make_simple_catvton_result((512, 768))
    person_image = make_simple_person_image((512, 768))

    # Call the function under test
    result, metadata = catvton_color_fidelity_spatial(
        catvton_result=catvton_result,
        original_garment=garment,
        person_image=person_image,
        garment_category="top",
        fidelity_strength=0.75,
    )

    # Verify that the result was generated successfully
    assert result is not None, "Function should return a result"
    assert (
        metadata.get("engine") == "catvton_color_fidelity_spatial"
    ), "Metadata should indicate spatial engine was used"

    # The realism pass adds fold darkening and edge shadows
    # We can't easily verify the exact visual effect, but we can verify:
    # 1. The function completes successfully
    # 2. The result is reasonable (not all black or corrupted)

    result_arr = np.array(result.convert("RGB"), dtype=np.float32)
    result_rgb_mean = float(result_arr.mean())

    # Result should be reasonable
    assert 20.0 < result_rgb_mean < 240.0, (
        f"Result RGB mean is {result_rgb_mean:.2f}, which is outside reasonable range. "
        f"This suggests realism pass or overall processing may have failed."
    )

    # Extract garment region
    height, width = result_arr.shape[:2]
    garment_region = result_arr[
        height // 4 : 3 * height // 4,
        width // 3 : 2 * width // 3,
    ]

    # Check that there is some variance in the garment region
    # (realism pass should add some darkening/shadows, creating variance)
    garment_variance = float(garment_region.var())

    # Variance should be > 0 (not completely uniform)
    # This suggests some shading/wrinkles were applied
    assert garment_variance > 0.1, (
        f"Garment region has very low variance ({garment_variance:.2f}), "
        f"suggesting realism pass may not have been applied"
    )

    print(
        f"✓ Realism pass working: result RGB mean={result_rgb_mean:.2f}, "
        f"garment variance={garment_variance:.2f}, pattern_score={pattern_score:.3f}"
    )


def test_preservation_other_modes_unchanged():
    """
    **Property 2: Preservation - Other Modes Unchanged**

    **Validates: Requirements 3.2**

    For virtual try-on requests with mode not in ["detail_fidelity", "blend"],
    the system SHALL continue to process according to original logic.

    **IMPORTANT**: This test should PASS on unfixed code (confirms baseline behavior to preserve).

    Note: The catvton_color_fidelity_spatial function is only called when mode is
    "detail_fidelity" or "blend". For other modes, different code paths are used.
    This test verifies that the function works correctly when called (which happens
    only in detail_fidelity/blend modes).
    """
    from app.services.tryon_v2.warp_engine import catvton_color_fidelity_spatial

    # Create a test garment
    garment = make_patterned_garment(
        (512, 512),
        "stars",
        [(255, 255, 255), (255, 0, 0)],
    )

    # Create test inputs
    catvton_result = make_simple_catvton_result((512, 768))
    person_image = make_simple_person_image((512, 768))

    # Call the function under test
    # (In actual usage, this function is only called for detail_fidelity/blend modes)
    result, metadata = catvton_color_fidelity_spatial(
        catvton_result=catvton_result,
        original_garment=garment,
        person_image=person_image,
        garment_category="top",
        fidelity_strength=0.75,
    )

    # Verify that the result was generated successfully
    assert result is not None, "Function should return a result"
    assert (
        metadata.get("engine") == "catvton_color_fidelity_spatial"
    ), "Metadata should indicate spatial engine was used"

    # Verify result is reasonable
    result_arr = np.array(result.convert("RGB"), dtype=np.float32)
    result_rgb_mean = float(result_arr.mean())

    assert (
        20.0 < result_rgb_mean < 240.0
    ), f"Result RGB mean is {result_rgb_mean:.2f}, which is outside reasonable range"

    print(f"✓ Function works correctly: result RGB mean={result_rgb_mean:.2f}")


def test_preservation_second_garment_processing():
    """
    **Property 2: Preservation - Second Garment Processing**

    **Validates: Requirements 3.6**

    When a second garment (garment_image_2) is provided, the system SHALL continue to
    process it correctly with pattern and color preservation.

    **IMPORTANT**: This test should PASS on unfixed code (confirms baseline behavior to preserve).

    This test verifies that the function can be called multiple times (once for each garment)
    and produces reasonable results for both garments.
    """
    from app.services.tryon_v2.warp_engine import catvton_color_fidelity_spatial

    # Create two different garments
    garment1 = make_patterned_garment(
        (512, 512),
        "stars",
        [(255, 255, 255), (255, 0, 0)],
    )

    garment2 = make_patterned_garment(
        (512, 512),
        "stripes",
        [(255, 255, 255), (0, 0, 255)],
    )

    # Create test inputs
    catvton_result = make_simple_catvton_result((512, 768))
    person_image = make_simple_person_image((512, 768))

    # Process first garment (top)
    result1, metadata1 = catvton_color_fidelity_spatial(
        catvton_result=catvton_result,
        original_garment=garment1,
        person_image=person_image,
        garment_category="top",
        fidelity_strength=0.75,
    )

    # Verify first garment result
    assert result1 is not None, "First garment should return a result"
    assert metadata1.get("engine") == "catvton_color_fidelity_spatial"

    result1_arr = np.array(result1.convert("RGB"), dtype=np.float32)
    result1_rgb_mean = float(result1_arr.mean())

    assert (
        20.0 < result1_rgb_mean < 240.0
    ), f"First garment result RGB mean is {result1_rgb_mean:.2f}, outside reasonable range"

    # Process second garment (bottom) - use result1 as the new catvton_result
    result2, metadata2 = catvton_color_fidelity_spatial(
        catvton_result=result1,  # Use first result as input
        original_garment=garment2,
        person_image=person_image,
        garment_category="bottom",
        fidelity_strength=0.75,
    )

    # Verify second garment result
    assert result2 is not None, "Second garment should return a result"
    assert metadata2.get("engine") == "catvton_color_fidelity_spatial"

    result2_arr = np.array(result2.convert("RGB"), dtype=np.float32)
    result2_rgb_mean = float(result2_arr.mean())

    assert (
        20.0 < result2_rgb_mean < 240.0
    ), f"Second garment result RGB mean is {result2_rgb_mean:.2f}, outside reasonable range"

    print(
        f"✓ Second garment processing working: "
        f"garment1 RGB={result1_rgb_mean:.2f}, garment2 RGB={result2_rgb_mean:.2f}"
    )


# ============================================================================
def test_lower_fidelity_clip_preserves_both_pants_legs():
    """Lower-body fidelity clipping must not drop one disconnected pants leg."""
    from app.services.tryon_v2.warp_engine import _build_lower_fidelity_clip_mask

    h, w = 160, 100
    layer_alpha = np.zeros((h, w), dtype=np.float32)
    layer_alpha[38:145, 22:43] = 1.0
    layer_alpha[38:145, 57:78] = 1.0
    garment_layer_present = layer_alpha > 0.12
    protected_by_mask = np.zeros((h, w), dtype=bool)
    changed_garment = np.zeros((h, w), dtype=bool)
    changed_garment[34:150, 18:82] = True

    catvton_mask_np = np.zeros((h, w), dtype=np.float32)
    catvton_mask_np[28:60, 20:80] = 1.0
    catvton_mask_np[60:145, 30:70] = 1.0

    clip = _build_lower_fidelity_clip_mask(
        catvton_mask_np,
        changed_garment,
        garment_layer_present,
        protected_by_mask,
        layer_alpha=layer_alpha,
        left_leg_box=(22, 38, 43, 145),
        right_leg_box=(57, 38, 78, 145),
    )

    assert clip is not None
    assert float(clip[75:130, 24:40].mean()) > 0.45
    assert float(clip[75:130, 60:76].mean()) > 0.45
    retained = float((clip > 0.08).sum()) / float(garment_layer_present.sum())
    assert retained > 0.70


def test_lower_texture_support_excludes_catvton_side_blocks():
    """Lower overlay texture support must not expand to CatVTON's full rectangle."""
    from app.services.tryon_v2.warp_engine import _build_lower_texture_support_mask

    h, w = 160, 100
    base_alpha = np.zeros((h, w), dtype=np.float32)
    base_alpha[38:145, 24:43] = 1.0
    base_alpha[38:145, 58:77] = 1.0
    protected_by_mask = np.zeros((h, w), dtype=bool)

    support = _build_lower_texture_support_mask(
        base_alpha,
        protected_by_mask,
        min_alpha=0.16,
        x_pad=5,
        y_pad=6,
    )

    assert support[70:130, 28:39].mean() > 0.90
    assert support[70:130, 62:73].mean() > 0.90
    assert support[70:130, 4:16].mean() == 0.0
    assert support[70:130, 84:96].mean() == 0.0


# ============================================================================
# Manual Test Runner for Preservation Tests
# ============================================================================


def main_preservation():
    """Run the preservation property tests manually."""
    print("=" * 80)
    print("Preservation Property Tests: Color Fidelity Pattern Loss Fix")
    print("=" * 80)
    print()
    print("These tests should PASS on unfixed code.")
    print("They confirm baseline behavior that must be preserved after the fix.")
    print()

    tests = [
        ("Solid Color Garments", test_preservation_solid_color_garments_unchanged),
        ("Face Protection", test_preservation_face_protection_continues_to_work),
        ("Hand Protection", test_preservation_hand_protection_continues_to_work),
        ("Realism Pass", test_preservation_realism_pass_continues_to_work),
        ("Other Modes", test_preservation_other_modes_unchanged),
        ("Second Garment", test_preservation_second_garment_processing),
    ]

    passed = 0
    failed = 0

    for test_name, test_func in tests:
        print(f"\nRunning: {test_name}")
        print("-" * 80)
        try:
            test_func()
            print(f"✓ PASSED: {test_name}")
            passed += 1
        except AssertionError as e:
            print(f"✗ FAILED: {test_name}")
            print(f"  Error: {e}")
            failed += 1
        except Exception as e:
            print(f"✗ ERROR: {test_name}")
            print(f"  Error: {type(e).__name__}: {e}")
            import traceback

            traceback.print_exc()
            failed += 1

    print()
    print("=" * 80)
    print(f"Preservation Tests Summary: {passed} passed, {failed} failed")
    print("=" * 80)

    if failed == 0:
        print()
        print("All preservation tests PASSED on unfixed code.")
        print("This confirms the baseline behavior to preserve.")
    else:
        print()
        print("Some preservation tests FAILED.")
        print("This may indicate issues with the test setup or unexpected behavior.")


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "preservation":
        main_preservation()
    else:
        main()
